// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwqhjgobwnzyegvqmpdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3cWhqZ29id256eWVndnFtcGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NzI2MjAsImV4cCI6MjA2MjE0ODYyMH0.C2S1JiAFBL3X7b8UoeCGpdU9UVEocbHKRZIMwFvi4EQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);